CREATE SEQUENCE TEST_RUN_INCREMENTER MINVALUE 1 MAXVALUE 999999999999
START WITH 1 INCREMENT BY 1;

COMMIT;

CREATE TABLE IF NOT EXISTS SAMPLE_RUNS(
TEST_RUN_SEQ NUMBER(10000) NOT NULL,
TEST_RUN_TIME TIMESTAMP NOT NULL,
TEST_RUN_USER VARCHAR2(50 CHAR),
CONSTRAINT SAMPLE_RUNS_PK PRIMARY KEY("TEST_RUN_SEQ")
);

COMMIT;